name: "KelevrA'S Photography LLC"
favicon: null
layout_spectrum: 0.10848293150775135
typography_spectrum: 0.42719410033896565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.982828474836424
  lightness: 0.1634456494357437
  saturation: 0.7563260036986321
  rhythmicContrast: 0.2286455393768847
purpose: []
